imports:
    - javascript
    - php

tools:
  external_code_coverage: true

filter:
  paths: [ src/* ]
  excluded-paths: [ spec/*, vendor/*, tests/*, bin/* ]

before_commands:
  - "pyrus install pecl/inotify && pyrus build pecl/inotify"
