<?php

/*
 * This file is part of the PhpGuard Listen project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace PhpGuard\Listen\Tests;


class TestCase extends \PHPUnit_Framework_TestCase
{
    static protected $tmpDir;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

        self::$tmpDir = sys_get_temp_dir().'/phpguard-test';
        if(!is_dir(self::$tmpDir)){
            mkdir(self::$tmpDir,0755,true);
        }
    }

    protected function mkdir($path)
    {
        @mkdir($path,0755,true);
    }
} 